import os  # Import the os module for file and directory operations

from src.note_model import NoteModel  # Import the NoteModel class

# Import functions from the same src/ folder
from . import create_note, search_notes, list_all_notes, link_notes
from . import NOTES_DIR_INBOX  # Directory where all the notes are stored
from . import NOTES_DIR_PERMA  # Directory where all the notes are stored

def main():
    """
    Main function for the Zettelkasten Note Manager command-line interface.

    This function presents a menu to the user, allowing them to create notes, search notes,
    list all notes, link notes, or exit the program. It processes user input to perform
    the chosen actions.

    Returns:
        None
    """
    while True:
        # Display the main menu
        print("Zettelkasten Note Manager")
        print("1. Create a new note")
        print("2. Search notes in inbox")
        print("3. Search notes in permanent notes")
        print("4. List all inbox notes")
        print("5. List all permanent notes")
        print("6. Link notes")
        print("7. Exit")
        
        # Get user choice
        choice = input("Enter your choice: ")
        
        # Handle user choices
        if choice == '1':
            # Create a new note
            title = input("Enter the title of the note: ")
            content = input("Enter the content of the note: ")
            tags = input("Enter tags (comma-separated): ").split(',')
            references = input("Enter references (comma-separated): ").split(',')
            thoughts = input("Enter any additional thoughts: ")

            # Create an instance of NoteModel
            new_note = NoteModel(
                title=title,
                zk_uid=None,  # UID should be generated by the create_note function or handled internally
                content=content,
                references=references,
                tags=tags,
                thoughts_connections=thoughts
            )

            # Call the create_note function with the note instance
            create_note(new_note)
            print("Note created successfully.")
        
        elif choice == '2':
            # Search notes
            keyword = input("Enter keyword to search in inbox: ")
            results = search_notes(keyword, NOTES_DIR_INBOX)
            print(f"Found {len(results)} notes:")
            for result in results:
                print(result)
        
        elif choice == '3':
            # Search notes
            keyword = input("Enter keyword to search in permanent notes: ")
            results = search_notes(keyword, NOTES_DIR_PERMA)
            print(f"Found {len(results)} notes:")
            for result in results:
                print(result)
        
        elif choice == '4':
            # List all notes
            notes = list_all_notes(NOTES_DIR_INBOX)
            print(f"Total notes: {len(notes)}")
            for note in notes:
                print(note)
        
        elif choice == '5':
            # List all notes
            notes = list_all_notes(NOTES_DIR_PERMA)
            print(f"Total notes: {len(notes)}")
            for note in notes:
                print(note)
        
        elif choice == '6':
            # Link notes
            note_uid = input("Enter the UID of the note to link from: ")
            linked_uids = input("Enter the UIDs of the notes to link to (comma-separated): ").split(',')
            link_notes(note_uid, linked_uids)
            print("Notes linked successfully.")
        
        elif choice == '7':
            # Exit the program
            break
        
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    # Ensure the notes directory exists
    os.makedirs(NOTES_DIR_INBOX, exist_ok=True)
    os.makedirs(NOTES_DIR_PERMA, exist_ok=True)
    
    # Start the main function
    main()
